### PR TITLE
updates to white list

### PR DESCRIPTION
**Pull request by ttcloopy**
Removal of characters and words which would allow profanity by proxy in game.

### CODE REVIEW

**Comment by judge2020** [comment]
I would hate not being able to say 'fork'

**Comment by Puggyblue999** [comment]
RIP being able to say "Chip 'n Dales"

**Comment by indiemini** [comment]
I don't like this. IMO, the mods can take care of toons that feel the need to find workarounds to the chat filter. However, with this update, (and I see what word you're trying to avoid being said), many words that can be critical to communication are removed. Also, I say Doggie all the time. No need to remove that one.

I DO agree with the "dickens" one, however.

**Comment by DarthMDev** [comment]
someone close this

**Pull request closed without merging**
