### PR TITLE
New ToonTask for Toontown Central

### PR DESCRIPTION
**Pull request by ghost**
This pull request adds a new toontask to the Toontown Central Playground.

### CODE REVIEW

**Comment by chandler14362** [comment]
Looks cool, good job :+1:. Ill look into this and determine if it will be included in the next update

**Comment by osxnick** [comment]
Looks great, thanks for contributing to TTF! :)

**Comment by ghost** [comment]
your welcome, buddy. :) I will probably contribute some more in the future.

**Comment by ghost** [comment]
@enigmeow @chandler14362 @Markgasus TTF Staff, it has been a while. Is this pull request ok to merge, because I can't work on new stuff for Toontown until this pull request gets merged.

**Comment by ttcloopy** [comment]
Just reviewing some stuff and came across this; has it been reviewed yet or was it lost in the mix of pulls?  The least we can do is let @Spiderlover know what is happening :)

**Comment by ghost** [comment]
ok, I changed the wording of the dialogue for the task. :)

**Comment by enigmeow** [comment]
So, this has been sitting here for a long time because people were objecting to additions which "add to the grind" without actually adding to the game.   It is good but  we're going to let it go

**Comment by ghost** [comment]
ok, thanks. @enigmeow I can work on something better for Toontown Fellowship now. :)

**Pull request closed without merging**
