### PR TITLE
Updated ToonDNA.py with Mega Colors.

### PR DESCRIPTION
**Pull request by TrueBlueDogemon**
This ToonDNA.py file has a new addition to the color list for both boys and girls: **MegaColors!**

MegaColors are what you think they are: colors. These two colors are designed with a key difference that separates them from the rest of the colors: **They are completely solid in the RGB scale.**

When I coded in MegaColors, I assumed it was a RGBA scale. I just hope it's not actually ARGB, otherwise it may not work. :P

Be prepared for more MegaColors! They're coming in the near future!

### CODE REVIEW

**Comment by DarthMDev** [comment]
mega green please

**Comment by TrueBlueDogemon** [comment]
Hey guys, I made the modifications to TTLocalizerEnglish and started a pull request. Go check it out and let me know if anything is missing (which at this point, I don't think there should be.)

**Comment by Chandler255** [comment]
I think we have enough colors, though.

**Comment by enigmeow** [comment]
We current have an issue where additional tool colors create additional toon color quests which are washing out other quests.  Once we have eliminated that issue, we will be open to more colors

**Pull request closed without merging**
