### PR TITLE
give a proper error if building fails

### PR DESCRIPTION
**Pull request by DarthMDev**
no syntax errors will 100% work

### CODE REVIEW

**Comment by ghost** [comment]
At least you added a try statement this time.

**Comment by DarthMDev** [comment]
lol

**Comment by chandler14362** [comment]
You should at least print the exception...

**Comment by DarthMDev** [comment]
?

**Comment by DarthMDev** [comment]
except:
 print 'Building the client failed please try again.'

**Comment by ghost** [comment]
except Exception,e:
  print "Error:"
  print e

Is probably close to what he had in mind

**Comment by DarthMDev** [comment]
Oh ok

**Comment by DarthMDev** [comment]
There lets hope that works.

**Pull request closed without merging**
