### PR TITLE
Added words to whitelist + hard factory

### PR DESCRIPTION
**Pull request by DissonancePM**
ya

### CODE REVIEW

**Comment by enigmeow** [comment]
I think a "brutal factory" is a great idea.. could we make this a boarding group option where if you DO a boarding group you get more merits?

**Comment by DarthMDev** [comment]
yes! this will make it easier to get merits

**Comment by DissonancePM** [comment]
@nkrypt there are no telemarkter or name dropper level 9s or 8

**Comment by DissonancePM** [comment]
@enigmeow ill attempt making a separate boarding group option for a brutal factory.

**Comment by DarthMDev** [comment]
LOL merge conflicts XD

**Comment by enigmeow** [comment]
LoudRob, Take a look at the BrutalVP (incorrectly named) branch..   it is a BrutalFactory implementation..  complete except for odds-and-ends..

**Comment by Chandler255** [comment]
@Loudrob (Going off of @enigmeow) The Brutal Factory is done and is amazingly put together.

**Comment by enigmeow** [comment]
I am going to add a facility that enables local server whitelists.   This way, we can each have our own without the never ending additions to the master git.. :)

**Pull request closed without merging**
