### PR TITLE
Random loading screen emotions

### PR DESCRIPTION
**Pull request by judge2020**
has been tested and works 100%
Should be easy adding in new emotions, just define a dictionary (above the list!) with the emote name and frame it should use, then add that dictionary to emotelist

### CODE REVIEW

**Comment by judge2020** [comment]
DON'T ACCEPT JUST YET! i decided to add in some animations which i will PR soon. And yes, the randomness works

**Comment by judge2020** [comment]
merging is good now

**Comment by judge2020** [comment]
the new animations : 
image
image
image

**Comment by enigmeow** [comment]
i love it..

**Comment by judge2020** [comment]
So, um, @enigmeow will TTF stay here since TTI is back?

**Comment by enigmeow** [comment]
yes..  TTFS will stay unless our user base leaves us.  I wish mark and kevin much luck and success..

**Comment by forest2001** [comment]
When is TTI returning?

**Comment by enigmeow** [comment]
i assume in the next week or so..

**Comment by ghost** [comment]
I think this would go along great with the loading screen style i submited a while back

**Comment by judge2020** [comment]
the album of these new emotions can be found [here](http://imgur.com/a/ldu1D)

**Comment by enigmeow** [comment]
Moved to local tree for testing
https://github.com/toontownfellowship/src/tree/PullRequest/115-random-emotions

**Comment by judge2020** [comment]
Thanks! ^_^

**Comment by judge2020** [comment]
If you want to @enigmeow you could change it to .pose(emotechosen['emote'], emotechosen['frame'])

**Pull request closed without merging**
