### PR TITLE
Few enhancements

### PR DESCRIPTION
**Pull request by LittleToonCat**
Yesterday, I decided to improve some things on Fellowship because I was bored. (Nonsense reason right? :P )

Anyways, This request includes changes to the tutorial quest script, and even make Tutorial Tom show a surprise muzzle when he sees a Flunky outside.

fellowship-screenshot-mon-feb-23-20-42-43-2015-8760
Looks better compared to the original right?

Also, I fixed Issue #120 I posted yesterday.
fellowship-screenshot-tue-feb-24-14-02-50-2015-7700

I might make more enhancements for TTF soon, but for now, this is all I got.

### CODE REVIEW

**Comment by enigmeow** [comment]
This looks good to me.. lemme see if I can fire up our PR tsar to look through these and catch up.. :)

**Comment by LittleToonCat** [comment]
@enigmeow  "tsar"?

**Comment by enigmeow** [comment]
I would like chan to review..  thats all.. lemme get him to take a look

**Comment by enigmeow** [comment]
Moved to a local branch for testing

https://github.com/toontownfellowship/src/tree/PullRequest/124

**Pull request closed without merging**
