### PR TITLE
New magic word unlimitedgags

### PR DESCRIPTION
**Pull request by DarthMDev**
basically you dont lose gags

### CODE REVIEW

**Comment by enigmeow** [comment]
For some reason this is including your SOS change as well.. isn't that in the other branch?

When you make a new branch, are you going back to master and making a new branch so that it just includes your changes?

**Comment by mgracer48** [comment]
if i dont go backt to master it would do the change too

**Comment by mgracer48** [comment]
got an idea if you do it if you can revert the sos change then when u want it add back in

**Comment by DarthMDev** [comment]
there its reverted

**Comment by DissonancePM** [comment]
please test your commits before making a pull request

**Comment by mgracer48** [comment]
hard to test when i cant even start astron server

**Comment by Kevman95** [comment]
Please stop giving me cancer. Thank you.

**Comment by mgracer48** [comment]
please stop being rude, thank you

**Comment by nkrypt** [comment]
your commits are cancer just quit please

**Comment by mgracer48** [comment]
omg i cant even help a game without being harrassed

**Comment by nkrypt** [comment]
YOU AREN'T HELPING! YOU'RE BREAKING EVERYTHING JUST FOR A COMMIT COUNT!

**Comment by Kevman95** [comment]
^^^^^^^

**Comment by mgracer48** [comment]
commit count? no im not trying to break everything jesus

**Comment by judge2020** [comment]
@nkrypt is right, you're what forum peeps call a 'post whore'.

What you need to do is look at the [third party section](https://github.com/toontownfellowship/ThirdParty)'s read me which tells you how to run the server

**Comment by Kevman95** [comment]
I swear, one line cancer commits...and just....i cant explain how much stuff ive seen within the past hour that i just wanna break my keyboard over.

This git needs to be cleaned up pronto. And rules need to be properly established.

**Comment by ghost** [comment]
Go back to "developing" Toontown World Online, please. You can make these commits there.

**Comment by mgracer48** [comment]
Man i wish i could delete this past

**Comment by judge2020** [comment]
Yep, but git is forever.

**Pull request closed without merging**
