### PR TITLE
Feature/report toon

### PR DESCRIPTION
**Pull request by enigmeow**
Persisting logging messages to the database

### CODE REVIEW

**Comment by judge2020** [comment]
Finally :smiley::smiley::smiley:

**Comment by enigmeow** [comment]
I cannot believe this was not working in TTI before..

**Comment by judge2020** [comment]
how do mods receive the report?

**Comment by enigmeow** [comment]
the message gets sent to the accountDB object ...  in the MySQL case, we just persist it to the db into a new table.  Over time, i assume we will refine this better

**Pull request merged**
