### PR TITLE
update camera angle branch

### PR DESCRIPTION
**Pull request by DarthMDev**

### CODE REVIEW

**Comment by judge2020** [comment]
Why include all this other junk in the PR?

**Comment by DarthMDev** [comment]
LOL this was from master branch XD dont blame me just pull request to merge master into this branch for more updateness

**Comment by enigmeow** [comment]
This normally is not how this is done.. You would instead merge master into your branch in your local environment before working on it and then push it at that point.  Doing this creates much confusion on what exactly the changes are in that particular branch.  I was incredibly confused when I first saw this

Is it your intention to work on this?

**Comment by enigmeow** [comment]
If you look, there is now a current camera-angle branch

**Pull request closed without merging**
