### PR TITLE
Update MoleHill.py

### PR DESCRIPTION
**Pull request by allenhagen**
Fixed Mole Hill so you can actually stomp them

### CODE REVIEW

**Comment by chandler14362** [comment]
Have you **fully** tested this?

**Comment by allenhagen** [comment]
Yes, I tested it with several different species to make sure the Moles acts just like they did in TTO. No more Toons popping up over the Moles and falling off without the satisfaction of a successful stomp.

**Comment by DarthMDev** [comment]
this might be the problem with collisions glitch

**Comment by allenhagen** [comment]
What kind of glitch is being experienced?

**Pull request merged**
