### PR TITLE
Newemotionforloadingscreen

### PR DESCRIPTION
**Pull request by DarthMDev**
I think this would be kinda funny. Get it? XD

### CODE REVIEW

**Comment by DissonancePM** [comment]
Please ONLY include the change mentioned in the title in your pull request. And it seems apparent you don't test your changes before you make a pull request.

**Comment by DarthMDev** [comment]
like i said i cant seem to make it so it doesnt do that commit it sucks :(

**Comment by judge2020** [comment]
Again, please use the [guide](https://github.com/toontownfellowship/ThirdParty/blob/master/README.md) for running the source to test your commits

**Comment by DarthMDev** [comment]
i installed dependencies and all that

**Comment by DissonancePM** [comment]
Remove your fork, and refork. And actually make changes that you are 100 percent sure work.

**Comment by DarthMDev** [comment]
this should 100 percent work

**Comment by judge2020** [comment]
You need to make sure that frame 135 laugh is a frame that shows the laugh emotion good, because 135 was the good frame for bored and it might not be the good frame for laugh

**Comment by DarthMDev** [comment]
ah makes sense

**Comment by DissonancePM** [comment]
Don't say "it should". Actually test your changes.

**Comment by ghost** [comment]
WTF

**Comment by Chandler255** [comment]
Sigh.

**Comment by judge2020** [comment]
by the way, this is using your laugh code:
image

**Pull request closed without merging**
