### PR TITLE
add an else statement for if the building fails

### PR DESCRIPTION
**Pull request by DarthMDev**

### CODE REVIEW

**Comment by DarthMDev** [comment]
my god this is embarrassing , can't believe i did this back in the day (facepalm)

**Comment by ghost** [comment]
I agree @mgracer48

**Comment by DissonancePM** [comment]
@mgracer48 you're not a god anymore?

**Comment by DarthMDev** [comment]
lol thank you loudrob  XD

**Comment by DarthMDev** [comment]
This is cancer jesus
what was i thinking

**Comment by DarthMDev** [comment]
@enigmeow wtf why did u merge this cancer i made LOL

**Comment by ghost** [comment]
@mgracer48 stop commenting on this shit

**Pull request merged**
