### PR TITLE
Allow numbers in name submissions

### PR DESCRIPTION
**Pull request by judge2020**
Haven't tested this with any submission system to make sure it's safe since i'm unsure of how to set one up

### CODE REVIEW

**Comment by meekzyr** [comment]
No, this will only open up the window for trolls.

**Comment by DissonancePM** [comment]
how many people would submit 69 or 420 or 360 or 21

**Comment by judge2020** [comment]
@nkrypt That's why there are mods to approve names and ban/kick rule breakers

**Comment by meekzyr** [comment]
@judge2020 That just makes name approving more stressful.

**Comment by ttcloopy** [comment]
I agree, no numbers in name submissions, if letters won't do it for you, it is not a name that will be approved.

**Comment by chandler14362** [comment]
Numbers will **never** be allowed in names.

**Pull request closed without merging**
