### PR TITLE
Added 3-starred SOS rewards for Brutal Factories.

### PR DESCRIPTION
**Pull request by LittleToonCat**
F.I.Y This is actually my commit, but I had problems pushing it to a different branch, but @enigmeow resolved it, so many thanks to him. :D

### CODE REVIEW

**Comment by midnightstrikes** [comment]
Very cool idea, I may be the only one but I feel 3 star cards might be too big of a reward. I can't exactly tell though because I myself have not been in a brutal factory but I think it might be a little op. Maybe a new tier card (still 3 star I guess) could be made for this purpose and added as just rewards for brutal factories (such as new sos were made for field offices). Just my two cents, like the idea though

**Comment by judge2020** [comment]
@midnightstrikes I think 3 star is fine, because a 4/5 star would be too high and the stupid rewards field offices got are too low (not even saying how they were NEVER used)

**Comment by midnightstrikes** [comment]
@judge2020 I guess you are right, I just feel some of the three star would be a little overpowered (barbara seville, nancy gas)

**Comment by alexanderr** [comment]
Theres no need for the isBrutal flag as all brutal factories are of the DistributedBrutalFactoryAI object, It would be best to override the setVictors method in DistributedBrutalFactoryAI since its already inherited.

```
def setVictors(self, victorIds):
    DistributedFactoryAI.DistributedFactoryAI.setVictors(self, victorIds)
    #Insert SOS reward code here
```

**Pull request merged**
