### PR TITLE
create burger king playground

### PR DESCRIPTION
**Pull request by DarthMDev**
for burger king lovers.

### CODE REVIEW

**Comment by mgracer48** [comment]
if u dont merge u dont like burger king :'(

**Comment by judge2020** [comment]
Please no

**Comment by enigmeow** [comment]
This seems rather incomplete.. We need to have the corresponding resource update that includes

1) A proper burger king playground
2) A path to it from the construction zone..
3) 3 new streets...
4) The burger king character walking those streets...
5) Toon tasks associated with it..
6) and a burger king boss battle...

**Comment by mgracer48** [comment]
It was a joke lol but feel free to make it

**Comment by DissonancePM** [comment]
it should've been a kfc playground

**Comment by DarthMDev** [comment]
LOL ^

**Pull request closed without merging**
