### PR TITLE
Tti to ttf

### PR DESCRIPTION
**Pull request by DarthMDev**
oh crud conflicts

### CODE REVIEW

**Comment by DissonancePM** [comment]
this can cause issues. are you sure you have renamed everything correctly?

**Comment by DarthMDev** [comment]
why do u say that i made sure to correctly change every file from TTI to TTF

**Comment by DissonancePM** [comment]
@mgracer48 every single one?

**Comment by DarthMDev** [comment]
not every one but mostly the ones that are important

**Comment by DissonancePM** [comment]
The reason there are merge conflicts is because of all the commits that aren't necessarily needed before this commit https://github.com/mgracer48/src/commit/e9a0cf77c4bcc8f750c0446c65a43d4b8f7c1323
Try only renaming the TTI things in a new fork.

**Comment by DarthMDev** [comment]
hmm ok

**Comment by enigmeow** [comment]
This is not the first time we've seen this kind of commit and originally, it was rejected because we were expecting to push back into TTI tree..  I am now pretty sure we're not going to do that

Lemme confirm we are taking this step but I was thinking it myself..

**Comment by DarthMDev** [comment]
lol not redoing it so i guess forget this unless devs can solve the merge conflicts

**Comment by enigmeow** [comment]
I can solve the merge conflict..

**Comment by DarthMDev** [comment]
awesome

**Comment by enigmeow** [comment]
https://github.com/toontownfellowship/src/tree/mgracer48-TTI_to_TTF

**Comment by enigmeow** [comment]
So, this creates potentially a huge downstream conflict with everybody who forks off of us..

What do people think about this?

**Comment by enigmeow** [comment]
mgracer48, you on skype?

**Comment by DarthMDev** [comment]
i do have skype

**Comment by DarthMDev** [comment]
why do you ask?

**Comment by DarthMDev** [comment]
im mgracer48

**Pull request closed without merging**
