### PR TITLE
Allow TP Access Task at Beginning of TTC

### PR DESCRIPTION
**Pull request by osxnick**
Much more convenient if toon wanders off and can't get back. Tested- it works perfectly.

### CODE REVIEW

**Comment by enigmeow** [comment]
You can always just teleport to the raceway. can't you?

**Comment by ghost** [comment]
yeah, you can. You still waste a couple of minutes from walking through the tunnel in the raceway though.

**Comment by enigmeow** [comment]
I have no personal issue with this change.  I don't think it changes the game balance at all and it does improve the life of small toons a little. ..  i'll let chan chime in.. :)

**Comment by ghost** [comment]
yeah, I agree. This change helps small toons a bit.

**Comment by Chandler255** [comment]
I like the idea but, the point of being a small toon is to learn how the game works. Plus, if we did this then, Goofy Speedway would be visited ALOT more less ; - ;

**Comment by osxnick** [comment]
This was in Test Toontown though :/

**Comment by chandler14362** [comment]
Are you sure this works %100? I haven't tested it yet, just curious.

**Comment by osxnick** [comment]
I saved it, made a new toon, and went through the entire toontorial process. After making a friend, the HQ officer automically assigns you the teleport access task. After completing the task, you get the regular Gag Training task like normal. It is tested.

**Comment by chandler14362** [comment]
@xJollibee I don't think you should be forced to get the task before gag training. Ill probably change it so that you get it as an option in one of the first set of tasks.

**Pull request closed without merging**
