### PR TITLE
Updated Loading Screen! (With TOON TIPS) (Fixed Tip Wordwrapping and size)

### PR DESCRIPTION
**Pull request by ghost**
I recently submitted a pull request for this loading screen, however there were some things I had to fix, The tip size, and the word wrapping! Here is the new pull request
http://i.imgur.com/bq4QsCU.png
Note: The logo in this pull request will still show the Toontown Fellowship logo, not the Toontown Reimagined logo that is present nor the Toontown Central loading screen background

### CODE REVIEW

**Comment by DarthMDev** [comment]
hey gamesandrew are u like reimagined owner or dev?

**Comment by DarthMDev** [comment]
if so i would like to be a coder for that

**Comment by DarthMDev** [comment]
because i want to help a toontown server be better :D

**Comment by DarthMDev** [comment]
and i mean i think the job would help me in my career in coding  , help me improve my skills :)

**Comment by ghost** [comment]
Working for a server based off code from a server based off code from another server based off code from a defunct game won't really improve your coding skills if you don't even know python. Don't even try to disagree, I saw your except statement without even a try statement. Please learn python before making 20 useless pull requests where most likely only 1 or if you're lucky 2 will be pushed to the master branch.

**Comment by enigmeow** [comment]
Moved to local branch for testing

https://github.com/toontownfellowship/src/tree/pullrequest/79-updated-loading-screen

**Pull request closed without merging**
