### PR TITLE
More laff for future content

### PR DESCRIPTION
**Pull request by DarthMDev**
i mean the current one just doesnt seem like enough if we make cognation and a new playground

### CODE REVIEW

**Comment by judge2020** [comment]
Ya know, you DO have to make some way to get 156?...

**Comment by DarthMDev** [comment]
its a placeholder for future content for us :/

**Comment by judge2020** [comment]
since this is such a small edit, when new content is added we'll change the number ourselves

**Comment by DarthMDev** [comment]
makes sense

**Comment by DissonancePM** [comment]
i like how your pull request is filled with reverts.

**Comment by ghost** [comment]
Oh. i see this number might have been stolen from me questionmark?

**Pull request closed without merging**
