### PR TITLE
Magic cat op damage :D

### PR DESCRIPTION
**Pull request by DarthMDev**

### CODE REVIEW

**Comment by judge2020** [comment]
I am 100% certain this PR will not be accepted

**Comment by mgracer48** [comment]
why is that judge?

**Comment by judge2020** [comment]
because it adds in elections https://github.com/mgracer48/src/blob/magic_cat_and_trapcat/toontown/election/ElectionGlobals.py

**Comment by mgracer48** [comment]
oh lol hmm i got an idea

**Comment by mgracer48** [comment]
so i reverted those things you think it can  be merged now?

**Comment by nkrypt** [comment]
Stop making so many irrelevant commits in one PR :-1:

**Comment by mgracer48** [comment]
idk how to delete those commits

**Comment by nkrypt** [comment]
Just give up on making PRs please. It's hideous.

**Comment by mgracer48** [comment]
dont have to be rude

**Comment by ghost** [comment]
Who is adding this stuff, if you want to do little party tricks with SOS cards in your private space, go for it, but don't push it to github.

**Pull request closed without merging**
