### PR TITLE
Tweaks to certain quest requirements

### PR DESCRIPTION
**Pull request by Apple0726**
Certain requirements for tasks have been nerfed so players would actually select non-generic tasks. Some storyline tasks have been nerfed as well such as Hysterical Harry.

I really hope I didn't break anything as I made tons of changes (and I don't have anything to test the code).

### CODE REVIEW

**Comment by enigmeow** [comment]
arn't we making this game a little to easy?  at some point?  You can get through all these tasks in a week or two...

**Comment by judge2020** [comment]
@enigmeow Your comment could be right... But that's the way toontown goes- if it is too easy, players may get to the end of the game too fast where the player gets bored, while if you make it too grindy and slow the player won't keep coming back to play. This is ultimately why toontown was shut down. If this wasn't a problem then disney may have put more money and effort into fixing the injector, lowering client control, and increased advertising.

...They could have also made a PvP thing, which would have been awesome and would have saved the game.

**Comment by enigmeow** [comment]
We debated this one and decided that, while we agreed some of the tasks could be nerfed,  this really changes the whole game and it is a bit over the line.  Just too many tasks were reduced to almost nothing

It might be easier to just add a quest multiplier so that people can configure this on a per server bases...

**Comment by Apple0726** [comment]
The main thing I wanted is choosing different types of tasks is more of a personal choice than "logical" choice (just like choosing trap or drop): nobody would take a 200 5 story bossbot building task or 280 tightwads over a 500 cogs one.
However yes, I do think I nerfed the tasks too much, but I just wanted to make sure all types of tasks are (almost) equivalent in difficulty/time needed with the generic any-type cogs anywhere tasks.

**Pull request closed without merging**
