### PR TITLE
Remove useless cog suit part reward

### PR DESCRIPTION
**Pull request by judge2020**
no longer needed

### CODE REVIEW

**Comment by chandler14362** [comment]
Have you made sure that this class isn't used ANYWHERE in the code?

**Comment by meekzyr** [comment]
@chandler14362 I found two instances of it still!
16896e27158d53ba9a5371f254614e6c

**Comment by judge2020** [comment]
@nkrypt nice ctrl+f!
that line of code is also unnecessary due to it seeing if the reward is a cog suit part, while these tasks have been removed

**Comment by meekzyr** [comment]
@judge2020 ACTUALLY, it's Ctrl+H :)

Plus, this code STILL crashes the AI!

:-1:

**Pull request closed without merging**
