### PR TITLE
batch files for easier development

### PR DESCRIPTION
**Pull request by judge2020**

### CODE REVIEW

**Comment by LittleToonCat** [comment]
:+1: That'll make starting the servers and the client a lot quicker. I hate having to hit enter at every prompt.

**Comment by nkrypt** [comment]
This isn't really necessary.. You're barely doing any work by pressing Enter...

**Comment by DarthMDev** [comment]
why is this not merged! This is great.

**Comment by enigmeow** [comment]
I will move some of these around tonight and merge them.  Objections were made with there being .bat files in non win32 directories

**Comment by judge2020** [comment]
@enigmeow i'd be happy to move the ones in root to \win32 if you'd like

**Comment by judge2020** [comment]
fixed @enigmeow

**Pull request merged**
