### PR TITLE
Remove linux folder

### PR DESCRIPTION
**Pull request by DarthMDev**
whats the point of this folder they both look the same to me

### CODE REVIEW

**Comment by enigmeow** [comment]
Why remove linux?  I use linux as my primary development platform...

**Comment by judge2020** [comment]
Please just leave.

Sh is the .bat for Linux machines

**Comment by DarthMDev** [comment]
yea ik but darwin has the same sh thing

**Comment by DarthMDev** [comment]
so i renamed it darwin&linux i dont know how that made u mad :(

**Comment by DarthMDev** [comment]
@enigmeow  because darwin has the same sh stuff why waste space when we can keep it in one folder

**Comment by DarthMDev** [comment]
oh nvm i see why, they are different  sh files my bad :/

**Comment by enigmeow** [comment]
np.. i wasn't mad.. I was confused.. :)

**Pull request closed without merging**
