### PR TITLE
a gui for cogs' levels

### PR DESCRIPTION
**Pull request by DarthMDev**
dont merge its not done

### CODE REVIEW

**Comment by judge2020** [comment]
you're not supposed to make a PR if something's not done

**Comment by DarthMDev** [comment]
ah buts its a start

**Comment by judge2020** [comment]
still, don't make a PR on an unfinished feature. this suggests an AI panic right now

**Comment by DarthMDev** [comment]
kk

**Comment by DissonancePM** [comment]
Please make your code have proper grammar.

**Comment by DarthMDev** [comment]
lol kk

**Pull request closed without merging**
