### PR TITLE
Updated astron with fixes

### PR DESCRIPTION
**Pull request by DarthMDev**
thought this would be helpful :)

### CODE REVIEW

**Comment by DarthMDev** [comment]
yes its mongodb compatiable

**Comment by judge2020** [comment]
Have you tested your changes? It seems like you're PR'ing too fast to test your changes in full

**Comment by DissonancePM** [comment]
These should be put in thirdparty repo.

**Comment by DarthMDev** [comment]
got it going be put in third party and how i know it works is i used it on former server :)  which i quited  it was called toontown world

**Pull request closed without merging**
